import 'package:untitled1/hive/tokens.dart';

final List<Tokens> kBuiltInSolanaTokens = [
  Tokens(image: 'assets/images/W_SOL.png', title: 'SOL', subtitle: 'Solana', price: '0.00', number: '0.00', toadd: true, tokenAddress: 'SOL'),
  Tokens(
    image: 'https://assets.coingecko.com/coins/images/325/standard/Tether.png?1696501661',
    title: 'USDT',
    subtitle: 'USDT',
    price: '0.00',
    number: '0.00',
    toadd: true,
    tokenAddress: 'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB',
  ),
  Tokens(
    image: 'assets/images/W_SOL.png',
    title: 'Wrapped SOL',
    subtitle: 'SOL',
    price: '0.00',
    number: '0.00',
    toadd: true,
    tokenAddress: 'So11111111111111111111111111111111111111112',
  ),
  Tokens(
    image: 'https://arweave.net/hQiPZOsRZXGXBJd_82PhVdlM_hACsT_q6wqwf5cSY7I',
    title: 'BONK',
    subtitle: 'Bonk',
    price: '0.00',
    number: '0.00',
    toadd: true,
    tokenAddress: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
  ),
  Tokens(
    image: 'https://metadata.jito.network/token/jto/image',
    title: 'JITO',
    subtitle: 'JTO',
    price: '0.00',
    number: '0.00',
    toadd: true,
    tokenAddress: 'jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL',
  ),
  Tokens(
    image: 'assets/images/dogwifhat.png',
    title: 'dogwifhat',
    subtitle: 'WIF',
    price: '0.00',
    number: '0.00',
    toadd: true,
    tokenAddress: 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',
  ),
  Tokens(
    image: 'https://assets.coingecko.com/coins/images/6319/standard/usdc.png?1696506694',
    title: 'USDC',
    subtitle: 'USDC',
    price: '0.00',
    number: '0.00',
    toadd: true,
    tokenAddress: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
  ),
];
